CREATE TABLE experience_skill
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted       BOOLEAN                                 NOT NULL,
    experience_id BIGINT                                  NOT NULL,
    skill_son_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_experience_skill PRIMARY KEY (id)
);

ALTER TABLE experience_skill
    ADD CONSTRAINT uc_a23305a3a5c4d80ef49092f99 UNIQUE (experience_id, skill_son_id);

ALTER TABLE experience_skill
    ADD CONSTRAINT FK_EXPERIENCE_SKILL_ON_EXPERIENCE FOREIGN KEY (experience_id) REFERENCES experience (id);

ALTER TABLE experience_skill
    ADD CONSTRAINT FK_EXPERIENCE_SKILL_ON_SKILL_SON FOREIGN KEY (skill_son_id) REFERENCES skill_son (id);