CREATE TABLE futured_project_skill_relational
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted            BOOLEAN                                 NOT NULL,
    futured_project_id BIGINT                                  NOT NULL,
    skill_son_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_futured_project_skill_relational PRIMARY KEY (id)
);

ALTER TABLE futured_project_skill_relational
    ADD CONSTRAINT uc_ef586a8179605431f7ee36cca UNIQUE (futured_project_id, skill_son_id);

ALTER TABLE futured_project_skill_relational
    ADD CONSTRAINT FK_FUTURED_PROJECT_SKILL_RELATIONAL_ON_FUTURED_PROJECT FOREIGN KEY (futured_project_id) REFERENCES futured_project (id);

ALTER TABLE futured_project_skill_relational
    ADD CONSTRAINT FK_FUTURED_PROJECT_SKILL_RELATIONAL_ON_SKILL_SON FOREIGN KEY (skill_son_id) REFERENCES skill_son (id);