CREATE TABLE skill_type_relational
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    updated       TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    deleted       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    skill_id      BIGINT                                  NOT NULL,
    skill_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_skill_type_relational PRIMARY KEY (id)
);

ALTER TABLE skill_type_relational
    ADD CONSTRAINT uc_feebc2279a4f96b905ba99d3e UNIQUE (skill_id, skill_type_id);

ALTER TABLE skill_type_relational
    ADD CONSTRAINT FK_SKILL_TYPE_RELATIONAL_ON_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id);

ALTER TABLE skill_type_relational
    ADD CONSTRAINT FK_SKILL_TYPE_RELATIONAL_ON_SKILL_TYPE FOREIGN KEY (skill_type_id) REFERENCES skill_type (id);