CREATE TABLE home_label_relational
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted  BOOLEAN                                 NOT NULL,
    home_id  BIGINT                                  NOT NULL,
    label_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_home_label_relational PRIMARY KEY (id)
);

ALTER TABLE home_label_relational
    ADD CONSTRAINT uc_f45a3287a08a41dbec885443f UNIQUE (home_id, label_id);

ALTER TABLE home_label_relational
    ADD CONSTRAINT FK_HOME_LABEL_RELATIONAL_ON_HOME FOREIGN KEY (home_id) REFERENCES home (id);

ALTER TABLE home_label_relational
    ADD CONSTRAINT FK_HOME_LABEL_RELATIONAL_ON_LABEL FOREIGN KEY (label_id) REFERENCES label (id);