CREATE TABLE skill_son_relational
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted         BOOLEAN                                 NOT NULL,
    skill_id        BIGINT                                  NOT NULL,
    function_son_id BIGINT                                  NOT NULL,
    experience_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_skill_son_relational PRIMARY KEY (id)
);

ALTER TABLE skill_son_relational
    ADD CONSTRAINT uc_5948a4a738977786cd0f5b8fb UNIQUE (skill_id, function_son_id);

ALTER TABLE skill_son_relational
    ADD CONSTRAINT FK_SKILL_SON_RELATIONAL_ON_EXPERIENCE FOREIGN KEY (experience_id) REFERENCES experience (id);

ALTER TABLE skill_son_relational
    ADD CONSTRAINT FK_SKILL_SON_RELATIONAL_ON_FUNCTION_SON FOREIGN KEY (function_son_id) REFERENCES skill_son (id);

ALTER TABLE skill_son_relational
    ADD CONSTRAINT FK_SKILL_SON_RELATIONAL_ON_SKILL FOREIGN KEY (skill_id) REFERENCES skill (id);