CREATE TABLE blog
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    created                 TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    updated                 TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    deleted                 BOOLEAN                                     NOT NULL,
    title                   VARCHAR(255)                                NOT NULL,
    title_eng               VARCHAR(255)                                NOT NULL,
    clean_url_title         VARCHAR(255)                                NOT NULL,
    description_short       VARCHAR(255)                                NOT NULL,
    description             TEXT                                        NOT NULL,
    description_short_eng   VARCHAR(255)                                NOT NULL,
    description_eng         TEXT                                        NOT NULL,
    blog_type_id            BIGINT                                      NULL,
    image_url_id            BIGINT                                      NULL,
    video_url_id            BIGINT                                      NULL,
    CONSTRAINT pk_blog PRIMARY KEY (id)
);

ALTER TABLE blog
    ADD CONSTRAINT FK_BLOG_ON_BLOG_TYPE FOREIGN KEY (blog_type_id) REFERENCES blog_type (id);

ALTER TABLE blog
    ADD CONSTRAINT FK_BLOG_ON_IMAGE_URL FOREIGN KEY (image_url_id) REFERENCES image_url (id);

ALTER TABLE blog
    ADD CONSTRAINT FK_BLOG_ON_VIDEO_URL FOREIGN KEY (video_url_id) REFERENCES video_url (id);