CREATE TABLE basic_data
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted            BOOLEAN                                 NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    others_name        VARCHAR(255)                            NOT NULL,
    first_surname      VARCHAR(255)                            NOT NULL,
    others_sur_name        VARCHAR(255)                        NOT NULL,
    date_birth         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    located            VARCHAR(255)                            NOT NULL,
    start_working_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    greeting           VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    instagram          VARCHAR(255)                            NOT NULL,
    linkedin           VARCHAR(255)                            NOT NULL,
    x                  VARCHAR(255)                            NOT NULL,
    github             VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_basic_data PRIMARY KEY (id)
);