CREATE TABLE blog
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted           BOOLEAN                                 NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    clean_url_title   VARCHAR(255)                            NOT NULL,
    description_short VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_blog PRIMARY KEY (id)
);