CREATE TABLE experience
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted     BOOLEAN                                 NOT NULL,
    year_start  date                                    NOT NULL,
    year_end    date                                    NOT NULL,
    company     VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_experience PRIMARY KEY (id)
);