CREATE TABLE home
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted                     BOOLEAN                                 NOT NULL,
    greeting                    VARCHAR(255)                            NOT NULL,
    greeting_eng                VARCHAR(255)                            NOT NULL,
    image_id                    BIGINT,
    button_work_label           VARCHAR(255)                            NOT NULL,
    button_work_label_eng       VARCHAR(255)                            NOT NULL,
    button_contact_label        VARCHAR(255)                            NOT NULL,
    button_contact_label_eng    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_home PRIMARY KEY (id)
);

ALTER TABLE home
    ADD CONSTRAINT FK_HOME_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image_url (id) ON DELETE SET NULL;

