CREATE TABLE futured_project
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted           BOOLEAN                                 NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    experience_id     BIGINT                                  NOT NULL,
    description_short VARCHAR(255)                            NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    image_list_url    VARCHAR(255)                            NOT NULL,
    image_url         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_futured_project PRIMARY KEY (id)
);

ALTER TABLE futured_project
    ADD CONSTRAINT FK_FUTURED_PROJECT_ON_EXPERIENCE FOREIGN KEY (experience_id) REFERENCES experience (id);