CREATE TABLE home
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted              BOOLEAN                                 NOT NULL,
    greeting             VARCHAR(255)                            NOT NULL,
    image_url            VARCHAR(255)                            NOT NULL,
    button_work_label    VARCHAR(255)                            NOT NULL,
    button_contact_label VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_home PRIMARY KEY (id)
);