CREATE TABLE skill_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted     BOOLEAN                                 NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    name_eng    VARCHAR(255)                            NOT NULL,
    CONSTRAINT  pk_skill_type PRIMARY KEY (id)
);